link via doxygen tags
JuliaIO/HDF5.jl pull request #1044
Opened 2023-01-25 18:27 UTC by simonbyrne

This was my effort at #1029, as an alternative to #1043. It adds a pass to Documenter that expands `@doxygen` tags based on XML xpaths.

Still not quite complete, as the xpaths are a bit complicated.

2023-01-26 04:21 UTC, mkitti commented
What happens when someone accesses the help in REPL or in VSCode? Does the docstring expand somehow?

2023-01-26 04:27 UTC, simonbyrne commented
At the moment it will be empty, which is not ideal. I can change it so that it displays the function name (same as how `@ref` links are displayed)

2023-01-26 05:30 UTC, simonbyrne commented
Hmm, I was wrong. It looks like only `@ref` tags are rendered as such. Any other tags will be rendered the same as http links, e.g. `[`fname`](@doxygen)` will be rendered as
```
fname (@doxygen])
```

2023-01-26 09:45 UTC, mkitti commented
```
help?> HDF5.API.h5d_get_chunk_info
  h5d_get_chunk_info(dataset_id::hid_t, fspace_id::hid_t, index::hsize_t, offset::Ptr{hsize_t}, filter_mask::Ptr{Cuint}, addr::Ptr{haddr_t}, size::Ptr{hsize_t})

  External links
  ≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡

    •  (@doxygen /tagfile/compound[name='H5D']/member[name='H5Dget_chunk_info']).
```

I think we should make URL docstrings usable from the REPL and the only way I know how  to do that is interpolate the URLs in at generation time. While we could dynamically load the tag file at package init, I don't see a clear advantage for doing that over just statically including the URL in the doc string. Perhaps one thing might be changing the URLs to match the version of the HDF5 library loaded. The URLS should be accessible beyond just the Documenter.jl generated docs.

I do like the xpath approach though.

2023-01-26 09:47 UTC, mkitti commented
Do not forget about these URLs as well:
https://github.com/JuliaIO/HDF5.jl/blob/2796b08741b6c5fbfda12435b3733e78abe19abc/gen/gen_wrappers.jl#L125

2023-01-26 09:49 UTC, mkitti requested changes
1. I think we should include the hdf5.tag file in `git`.
2. Insert the URLs into the docstrings so they are visible in more than just the HTML docs.

2023-01-26 15:22 UTC, mkitti commented
Some symbols are not being resolved in the H5F, H5P, and H5T category. Might want to just to do `//member[name='$cfuncname']`.

<details>
<summary>List of undiscovered symbols, ignore the line citation. I've been editing this.</summary>

```julia
┌ Warning: No node for /tagfile/compound[name='H5F']/member[name='H5Fformat_convert']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for //member[name='H5Fformat_convert']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5F']/member[name='H5Fget_mdc_config']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5F']/member[name='H5Fget_mdc_hit_rate']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5F']/member[name='H5Fget_mdc_image_info']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5F']/member[name='H5Fget_mdc_logging_status']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5F']/member[name='H5Fget_mdc_size']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5F']/member[name='H5Fget_metadata_read_retry_info']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5F']/member[name='H5Fget_mpi_atomicity']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5F']/member[name='H5Freset_mdc_hit_rate_stats']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5F']/member[name='H5Fset_mdc_config']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5F']/member[name='H5Fset_mpi_atomicity']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5F']/member[name='H5Fstart_mdc_logging']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5F']/member[name='H5Fstart_swmr_write']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5F']/member[name='H5Fstop_mdc_logging']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5L']/member[name='H5Literate']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5L']/member[name='H5Literate1']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_alignment']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_alloc_time']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_append_flush']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_attr_creation_order']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_attr_phase_change']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_btree_ratios']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_buffer']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_cache']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_char_encoding']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_chunk']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_chunk_cache']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_chunk_opts']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_class']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_class_parent']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_copy_object']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_core_write_tracking']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_create_intermediate_group']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_data_transform']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_driver']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_driver_info']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_dset_no_attrs_hint']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_dxpl_mpio']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_edc_check']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_efile_prefix']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_elink_acc_flags']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_elink_cb']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_elink_fapl']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_elink_file_cache_size']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_elink_prefix']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_est_link_info']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_evict_on_close']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_external']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_external_count']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_family_offset']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_fapl_core']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_fapl_family']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_fapl_hdfs']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_fapl_multi']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_fapl_splitter']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile/compound[name='H5P']/member[name='H5Pget_fapl_ros3']
└ @ Main ~/.julia/dev/HDF5/docs/doxygen.jl:45
┌ Warning: No node for /tagfile [...]

2023-01-26 17:04 UTC, mkitti commented
Here we are doing a new query for each function thay we are trying to lookup. This means that we are likely O(N^2) with the number of XML elements.

My current thinking here is that we should just do a single XPath query to allow us to iterate over the members once and build a lookup table like I do in #1043. Basically refactor my for loop into a single iteration over `findall` call with a XPath.

We should check in the hdf5.tag file but not the intermediate lookup tables. The package should be able to be regenerated from the git repo alone without an active Internet connection.

I'm still not seeing the advantage of tying the URL construction with Documenter, especially because it would be useful to have the URLs available outside of docker.

2023-01-26 17:11 UTC, simonbyrne commented
> I'm still not seeing the advantage of tying the URL construction with Documenter, especially because it would be useful to have the URLs available outside of docker.

I think you're right, there's probably not much to be gained in this case. The main thing I wanted to avoid was making the XML parser an actual package dependency.

The only downside with doing it in the `gen` scripts is that you can't use it elsewhere (e.g. link to sections of the manual). Not sure the best way to do that.

2023-01-26 18:40 UTC, mkitti commented
> The only downside with doing it in the gen scripts is that you can't use it elsewhere (e.g. link to sections of the manual). Not sure the best way to do that.

We could retain file such as the group URLs linked below in git.

https://github.com/JuliaIO/HDF5.jl/blob/900517b2a4f82ba69806e9afb7fde21ff5fd5ae3/gen/DoxygenTagParser/hdf5_group_urls.tsv

We could then load this into a global Dict at the top level during precompile time, interpolate the needed values, and then empty the table Dict at the end of precomp.

2023-01-27 17:47 UTC, mkitti commented
My exploratory diff to this branch is currently here:
https://github.com/JuliaIO/HDF5.jl/compare/sb/doxygen-tag...mkitti:HDF5.jl:mk/doxygen-tag?expand=1

2023-05-01 15:31 UTC, mkitti commented
One thing about the xpath approach is that we do end up iterating over the tags more than once since each query starts a new iteration. It's not a very big deal in terms of performance though, which is not a huge consideration here.

2023-08-27 02:34 UTC, mkitti commented
Merged #1043 over this one. We should revisit this later though, especially with a pure-Julia XML parser. See #1043 comments.

2023-08-27 02:34 UTC, closed without merging